'use strict';
const scenarios=[
{name:'קפיץ ומשקולות',title:'איך אורך הקפיץ משתנה?',b:15,m:2,max:10,discrete:true,x:'מספר משקולות',y:'אורך הקפיץ (ס״מ)',unit:'ס״מ',rate:'ס״מ לכל משקולת',story:'אורך הקפיץ ללא משקולות הוא 15 ס״מ. כל משקולת שמוסיפים מאריכה אותו ב־2 ס״מ.'},
{name:'חימום מים',title:'איך טמפרטורת המים משתנה?',b:20,m:5,max:16,discrete:false,x:'זמן החימום (דקות)',y:'טמפרטורה (°C)',unit:'°C',rate:'מעלות בכל דקה',story:'הטמפרטורה ההתחלתית היא 20 מעלות. בכל דקת חימום הטמפרטורה עולה ב־5 מעלות.'},
{name:'תמונות בענן',title:'כמה מקום תופסות התמונות?',b:500,m:3,max:10,discrete:true,x:'מספר תמונות שנוספו',y:'נפח אחסון (MB)',unit:'MB',rate:'MB לכל תמונה',story:'בענן תפוסים מראש 500 MB. כל תמונה שמעלים תופסת עוד 3 MB.'},
{name:'סוללת הטלפון',title:'איך אחוז הסוללה משתנה?',b:100,m:-8,max:12.5,discrete:false,x:'זמן השימוש (שעות)',y:'אחוז הסוללה (%)',unit:'%',rate:'נקודות אחוז בכל שעה',story:'הסוללה טעונה ב־100%. בכל שעת שימוש הטעינה יורדת ב־8 נקודות אחוז.'}
];
const $=id=>document.getElementById(id),fmt=n=>Number(n.toFixed(2)).toLocaleString('en-US',{maximumFractionDigits:2});let index=0,b=15,m=2,x=0,max=10,timer=null,custom=false,geometry;
const value=t=>b+m*t;
function stop(){clearInterval(timer);timer=null;$('play').querySelector('span').textContent='הפעלת התהליך';$('play').setAttribute('aria-label','הפעלת התהליך');$('play').setAttribute('aria-pressed','false');}
function choose(i){stop();index=i;({b,m,max}=scenarios[i]);x=0;custom=false;$('initial').value=b;$('rate').value=m;$('error').textContent='';render();}
function select(v){x=Math.min(max,Math.max(0,scenarios[index].discrete?Math.round(v):Math.round(v*100)/100));render();}
function render(){const s=scenarios[index];document.querySelectorAll('[data-scenario]').forEach(el=>el.setAttribute('aria-pressed',+el.dataset.scenario===index));$('title').textContent=s.title;$('story').textContent=custom?`תהליך לחקר: ערך התחלתי ${fmt(b)} ${s.unit}; שינוי של ${fmt(m)} ${s.rate}.`:s.story;$('position-label').textContent=s.x;$('position').max=max;$('position').step=s.discrete?1:.1;$('position').value=x;$('position-value').textContent=fmt(x);$('result').textContent=`${s.y}: ${fmt(value(x))}`;$('prev').disabled=x<=0;$('next').disabled=x>=max;$('x-head').textContent=s.x;$('y-head').textContent=s.y;$('start-value').textContent=`${fmt(b)} ${s.unit}`;$('rate-value').textContent=`${fmt(m)} ${s.rate}`;$('rule').textContent=`y = ${fmt(b)} ${m<0?'−':'+'} ${fmt(Math.abs(m))}x`;$('rule').hidden=!$('show-rule').checked;$('domain-note').textContent=s.discrete?'נקודות נפרדות: מספר המשקולות או התמונות הוא מספר שלם.':index===3?'מודל של ירידה קבועה בטעינה; מוצגים רק ערכים שבין 0% ל־100%.':'מודל חימום בקצב קבוע; התצוגה מוגבלת ל־100°C.';
let vals=Array.from({length:Math.floor(max)+1},(_,i)=>i);if(max%1)vals.push(max);if(!vals.some(v=>Math.abs(v-x)<.001))vals.push(x);vals.sort((a,c)=>a-c);$('rows').innerHTML=vals.map(v=>`<tr class="${Math.abs(v-x)<.001?'active':''}"><td><button data-x="${v}" aria-label="בחירת ${fmt(v)} ${s.x}" aria-pressed="${Math.abs(v-x)<.001}">${fmt(v)}</button></td><td dir="ltr">${fmt(value(v))}</td></tr>`).join('');draw();}
function draw(){const s=scenarios[index],svg=$('graph'),w=svg.clientWidth,h=svg.clientHeight,L=58,R=w-22,T=42,B=h-58;const ymin=Math.min(0,b,value(max)),rawMax=Math.max(1,b,value(max)),rough=rawMax/5,power=10**Math.floor(Math.log10(rough)),tick=[1,2,5,10].find(v=>v*power>=rough)*power,ymax=Math.ceil(rawMax/tick)*tick+tick,px=v=>L+(R-L)*v/max,py=v=>B-(v-ymin)/(ymax-ymin)*(B-T);geometry={L,R,max};const line=(a,c,d,e,extra='')=>`<line x1="${a}" y1="${c}" x2="${d}" y2="${e}" ${extra}/>`;const txt=(a,c,t,anchor='middle')=>`<text x="${a}" y="${c}" text-anchor="${anchor}">${t}</text>`;let out=`<title>${s.title}</title><desc>${s.x} בציר האופקי, ${s.y} בציר האנכי. ערך התחלתי ${b}, שינוי ${m}.</desc>`;
for(let v=0;v<=ymax;v+=tick){out+=line(L,py(v),R,py(v),'stroke="#e6ebf1"')+txt(L-9,py(v)+5,fmt(v),'end');}const ticks=w<420?3:5;for(let i=0;i<=ticks;i++){let v=max*i/ticks;if(s.discrete)v=Math.round(v);out+=line(px(v),T,px(v),B,'stroke="#eef1f5"')+txt(px(v),py(0)+23,fmt(v));}out+=line(L,T,L,B,'stroke="#17365e" stroke-width="1.5"')+line(L,py(0),R,py(0),'stroke="#17365e" stroke-width="1.5"')+txt(L,20,s.y,'start')+txt((L+R)/2,h-6,s.x);
if(!s.discrete)out+=line(px(0),py(b),px(max),py(value(max)),'stroke="#17365e" stroke-width="3"');else for(let i=0;i<=max;i++)out+=`<circle cx="${px(i)}" cy="${py(value(i))}" r="4.5" fill="#17365e"/>`;
if($('steps').checked){let a=Math.min(x,Math.max(0,max-1)),end=Math.min(max,a+1);out+=line(px(a),py(value(a)),px(end),py(value(a)),'stroke="#6db580" stroke-width="3"')+line(px(end),py(value(a)),px(end),py(value(end)),'stroke="#832058" stroke-width="3"');}
out+=line(px(x),py(value(x)),px(x),py(0),'stroke="#832058" stroke-dasharray="4 5"')+line(L,py(value(x)),px(x),py(value(x)),'stroke="#832058" stroke-dasharray="4 5"')+`<circle cx="${px(x)}" cy="${py(value(x))}" r="8" fill="#e7b976" stroke="#832058" stroke-width="2.5"/>`;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=out;}
$('scenarios').innerHTML=scenarios.map((s,i)=>`<button data-scenario="${i}" aria-pressed="${i===0}">${s.name}</button>`).join('');$('scenarios').onclick=e=>{const el=e.target.closest('[data-scenario]');if(el)choose(+el.dataset.scenario);};$('rows').onclick=e=>{const el=e.target.closest('[data-x]');if(el){stop();select(+el.dataset.x);}};$('position').oninput=e=>{stop();select(+e.target.value);};$('prev').onclick=()=>{stop();select(x-1);};$('next').onclick=()=>{stop();select(x+1);};$('play').onclick=()=>{if(timer){stop();return;}if(x>=max)select(0);$('play').querySelector('span').textContent='עצירה';$('play').setAttribute('aria-label','עצירת התהליך');$('play').setAttribute('aria-pressed','true');timer=setInterval(()=>{select(x+(scenarios[index].discrete?1:.5));if(x>=max)stop();},650);};$('steps').onchange=draw;$('show-rule').onchange=render;$('reset').onclick=()=>choose(index);$('help').onclick=()=>{stop();$('dialog').showModal();};$('close').onclick=()=>$('dialog').close();$('graph').onclick=e=>{stop();const r=$('graph').getBoundingClientRect();select((e.clientX-r.left-geometry.L)/(geometry.R-geometry.L)*max);};
$('parameters').onsubmit=e=>{e.preventDefault();const nb=+$('initial').value,nm=+$('rate').value;let problem='';if(!Number.isFinite(nb)||!Number.isFinite(nm)||Math.abs(nb)>10000||Math.abs(nm)>1000)problem='הזינו ערך התחלתי עד 10,000 ושינוי בין ‎−1,000 ל־1,000.';else if(index===3&&(nb<=0||nb>100||nm>=0))problem='בסוללה: ערך התחלתי גדול מ־0 ועד 100, ושינוי שלילי.';else if(index===1&&(nb<0||nb>=100||nm<=0))problem='בחימום: טמפרטורה התחלתית מ־0 ועד פחות מ־100, ושינוי חיובי.';else if((index===0||index===2)&&(nb<0||nm<=0))problem='הזינו ערך התחלתי לא שלילי ושינוי חיובי.';if(problem){$('error').textContent=problem;return;}stop();b=nb;m=nm;max=index===3?b/-m:index===1?Math.min(16,(100-b)/m):10;if(max>24)max=24;x=0;custom=true;$('error').textContent='';render();};new ResizeObserver(draw).observe($('graph'));choose(0);
